services:
  app:
    image: nextjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    labels:
      portway.route.path: /
    environment:
      INTERNAL_API_KEY: XQkhZPEVXQ0LgJLr
      NEXT_PUBLIC_APP_URL: https://splithaven.com

      BETTER_AUTH_SECRET: voZW7ZzYqt1JWmGq
      BETTER_AUTH_URL: https://splithaven.com

      DATABASE_URL: postgres://postgres:postgres@db:5432/appdb

      TYPESENSE_API_KEY: XNggQlHChW0fawET
      TYPESENSE_HOST: typesense
      TYPESENSE_PORT: "8108"
      TYPESENSE_PROTOCOL: http

      S3_BUCKET: splithaven
      S3_ENDPOINT: https://25844977d6037335b3c892d222f54af2.r2.cloudflarestorage.com
      S3_PUBLIC_URL_BASE: https://media.splithaven.com
      S3_FORCE_PATH_STYLE: "false"
      S3_ACCESS_KEY_ID: 0d9bf74f7dcd3bf91cbd4c64f47a28b2
      S3_SECRET_ACCESS_KEY: cfb89fdcceb64eb3be6a16faaba936bb3fb3c88aae066bb727f0b6b71ec1d06e
      S3_REGION: auto

  db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql
    expose:
      - 5432

  typesense:
    image: typesense/typesense:29.0
    environment:
      - TYPESENSE_API_KEY=XNggQlHChW0fawET
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - typesense_data:/data
    expose:
      - 8108

  transcoder:
    image: transcoder
    build:
      context: ./transcoder
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/appdb?sslmode=disable
      S3_BUCKET: splithaven
      S3_ENDPOINT: https://25844977d6037335b3c892d222f54af2.r2.cloudflarestorage.com
      S3_PUBLIC_URL_BASE: https://media.splithaven.com
      S3_ACCESS_KEY_ID: 0d9bf74f7dcd3bf91cbd4c64f47a28b2
      S3_SECRET_ACCESS_KEY: cfb89fdcceb64eb3be6a16faaba936bb3fb3c88aae066bb727f0b6b71ec1d06e
      S3_REGION: auto
      S3_FORCE_PATH_STYLE: "false"

      # Resource Controls - Prevent OOM by limiting parallel operations
      # Max number of transcode jobs to process simultaneously (0 = auto-detect based on CPUs)
      WORKER_CONCURRENCY: "1"
      # Max number of tasks (HLS, poster, thumbnails, hover) to run in parallel per job
      # Lower value reduces memory spikes (default was 4, now 2 saves ~40-50% memory)
      MAX_PARALLEL_TASKS_PER_JOB: "1"
      # Max number of HLS renditions to encode simultaneously (e.g., 720p, 1080p)
      # Prevents transcoding all qualities at once which can cause OOM
      MAX_PARALLEL_RENDITIONS: "1"
      # Minimum free disk space (GB) required before starting a transcode job
      TEMP_DIR_MIN_FREE_GB: "10"
    deploy:
      resources:
        limits:
          memory: 6g
        reservations:
          memory: 6g

volumes:
  db_data:
  typesense_data:
